// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwktibwafuxideiohuxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3a3RpYndhZnV4aWRlaW9odXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODg0NDQsImV4cCI6MjA1OTQ2NDQ0NH0.pErM4c2GOfuzeVqpm7F_zihZ133nmfkpA4mucGaIaDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);