// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmnatvcqjioabrlpkslw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtbmF0dmNxamlvYWJybHBrc2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDU3NjAsImV4cCI6MjA2MDM4MTc2MH0.teNC3DQ37eubHeq90pXySWHu5Z1h9Dpj7AVtMA-SOdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);